# Generated by Django 4.2.29 on 2026-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0021_address_country_iso_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='tx_id',
            field=models.CharField(blank=True, help_text='Crypto Transaction ID zur Abstimmung mit dem Blockchain Explorer', max_length=200, verbose_name='TX ID'),
        ),
    ]
