# Generated by Django 4.2.29 on 2026-04-14 18:40

from django.db import migrations, models
import geno.models


def populate_member_ids(apps, schema_editor):
    Member = apps.get_model("geno", "Member")
    for i, member in enumerate(Member.objects.order_by("pk"), start=1):
        member.member_id = f"M-{i:05d}"
        member.save(update_fields=["member_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0022_add_tx_id_to_share'),
    ]

    operations = [
        # Step 1: Add member_id without unique constraint
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, default="", help_text='Wird automatisch vergeben (z.B. M-00001).', max_length=20, verbose_name='Mitglied-Nr.'),
        ),
        # Step 2: Populate existing members with sequential IDs
        migrations.RunPython(populate_member_ids, migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, help_text='Wird automatisch vergeben (z.B. M-00001).', max_length=20, unique=True, verbose_name='Mitglied-Nr.'),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='file',
            field=models.FileField(blank=True, help_text='Foto, Video oder Dokument hochladen (für KYC/Identifikation).', upload_to=geno.models.member_attribute_upload_to, verbose_name='Datei'),
        ),
        migrations.AddField(
            model_name='memberattributetype',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'Datei (Foto/Video/Dokument)')], default='text', max_length=10, verbose_name='Feldtyp'),
        ),
        migrations.AlterField(
            model_name='memberattribute',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wert'),
        ),
    ]
