# Generated by Django 4.2 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geno", "0023_member_id_and_attribute_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="quantity",
            field=models.DecimalField(
                decimal_places=18,
                default=1,
                max_digits=38,
                verbose_name="Anzahl",
            ),
        ),
    ]
